---
name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  yaml-lint:
    uses: ./.github/workflows/yaml-lint.yml

  action-lint:
    uses: ./.github/workflows/action-lint.yml
