---
name: 'govulncheck'

on:
  workflow_call

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run govulncheck
        uses: golang/govulncheck-action@dd0578b371c987f96d1185abb54344b44352bd58 # v1
