---
name: Vulnerability Scanning

on:
  workflow_call

jobs:
  govulncheck_job:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1
        with:
          go-package: ./...
